-- Adding comprehensive list of Indian universities and colleges for university selection
INSERT INTO universities (name, domain, approved) VALUES
-- IITs (Indian Institutes of Technology)
('Indian Institute of Technology Bombay', 'iitb.ac.in', true),
('Indian Institute of Technology Delhi', 'iitd.ac.in', true),
('Indian Institute of Technology Madras', 'iitm.ac.in', true),
('Indian Institute of Technology Kanpur', 'iitk.ac.in', true),
('Indian Institute of Technology Kharagpur', 'iitkgp.ac.in', true),
('Indian Institute of Technology Roorkee', 'iitr.ac.in', true),
('Indian Institute of Technology Guwahati', 'iitg.ac.in', true),
('Indian Institute of Technology Hyderabad', 'iith.ac.in', true),
('Indian Institute of Technology Indore', 'iiti.ac.in', true),
('Indian Institute of Technology Mandi', 'iitmandi.ac.in', true),
('Indian Institute of Technology Ropar', 'iitrpr.ac.in', true),
('Indian Institute of Technology Bhubaneswar', 'iitbbs.ac.in', true),
('Indian Institute of Technology Gandhinagar', 'iitgn.ac.in', true),
('Indian Institute of Technology Jodhpur', 'iitj.ac.in', true),
('Indian Institute of Technology Patna', 'iitp.ac.in', true),
('Indian Institute of Technology Varanasi (BHU)', 'iitbhu.ac.in', true),
('Indian Institute of Technology Palakkad', 'iitpkd.ac.in', true),
('Indian Institute of Technology Tirupati', 'iittp.ac.in', true),
('Indian Institute of Technology Bhilai', 'iitbhilai.ac.in', true),
('Indian Institute of Technology Goa', 'iitgoa.ac.in', true),
('Indian Institute of Technology Jammu', 'iitjammu.ac.in', true),
('Indian Institute of Technology Dharwad', 'iitdh.ac.in', true),

-- IIMs (Indian Institutes of Management)
('Indian Institute of Management Ahmedabad', 'iima.ac.in', true),
('Indian Institute of Management Bangalore', 'iimb.ac.in', true),
('Indian Institute of Management Calcutta', 'iimcal.ac.in', true),
('Indian Institute of Management Lucknow', 'iiml.ac.in', true),
('Indian Institute of Management Kozhikode', 'iimk.ac.in', true),
('Indian Institute of Management Indore', 'iimidr.ac.in', true),
('Indian Institute of Management Shillong', 'iimshillong.ac.in', true),
('Indian Institute of Management Rohtak', 'iimrohtak.ac.in', true),
('Indian Institute of Management Ranchi', 'iimranchi.ac.in', true),
('Indian Institute of Management Raipur', 'iimraipur.ac.in', true),
('Indian Institute of Management Trichy', 'iimtrichy.ac.in', true),
('Indian Institute of Management Udaipur', 'iimu.ac.in', true),
('Indian Institute of Management Kashipur', 'iimkashipur.ac.in', true),
('Indian Institute of Management Nagpur', 'iimnagpur.ac.in', true),
('Indian Institute of Management Visakhapatnam', 'iimv.ac.in', true),
('Indian Institute of Management Amritsar', 'iimamritsar.ac.in', true),
('Indian Institute of Management Bodh Gaya', 'iimbg.ac.in', true),
('Indian Institute of Management Sambalpur', 'iimsambalpur.ac.in', true),
('Indian Institute of Management Sirmaur', 'iimsirmaur.ac.in', true),
('Indian Institute of Management Jammu', 'iimjammu.ac.in', true),

-- NITs (National Institutes of Technology)
('National Institute of Technology Tiruchirappalli', 'nitt.edu', true),
('National Institute of Technology Karnataka', 'nitk.edu.in', true),
('National Institute of Technology Warangal', 'nitw.ac.in', true),
('National Institute of Technology Calicut', 'nitc.ac.in', true),
('National Institute of Technology Durgapur', 'nitdgp.ac.in', true),
('National Institute of Technology Rourkela', 'nitrkl.ac.in', true),
('National Institute of Technology Kurukshetra', 'nitkkr.ac.in', true),
('National Institute of Technology Jamshedpur', 'nitjsr.ac.in', true),
('National Institute of Technology Allahabad', 'mnnit.ac.in', true),
('National Institute of Technology Bhopal', 'manit.ac.in', true),
('National Institute of Technology Jalandhar', 'nitj.ac.in', true),
('National Institute of Technology Hamirpur', 'nith.ac.in', true),
('National Institute of Technology Srinagar', 'nitsri.ac.in', true),
('National Institute of Technology Silchar', 'nits.ac.in', true),
('National Institute of Technology Agartala', 'nita.ac.in', true),
('National Institute of Technology Arunachal Pradesh', 'nitap.ac.in', true),
('National Institute of Technology Delhi', 'nitdelhi.ac.in', true),
('National Institute of Technology Goa', 'nitgoa.ac.in', true),
('National Institute of Technology Manipur', 'nitmanipur.ac.in', true),
('National Institute of Technology Meghalaya', 'nitmeghalaya.ac.in', true),
('National Institute of Technology Mizoram', 'nitmz.ac.in', true),
('National Institute of Technology Nagaland', 'nitnagaland.ac.in', true),
('National Institute of Technology Patna', 'nitp.ac.in', true),
('National Institute of Technology Puducherry', 'nitpy.ac.in', true),
('National Institute of Technology Raipur', 'nitrr.ac.in', true),
('National Institute of Technology Sikkim', 'nitsikkim.ac.in', true),
('National Institute of Technology Uttarakhand', 'nituk.ac.in', true),
('National Institute of Technology Andhra Pradesh', 'nitandhra.ac.in', true),

-- IISc and IISERs
('Indian Institute of Science Bangalore', 'iisc.ac.in', true),
('Indian Institute of Science Education and Research Pune', 'iiserpune.ac.in', true),
('Indian Institute of Science Education and Research Kolkata', 'iiserkol.ac.in', true),
('Indian Institute of Science Education and Research Mohali', 'iisermohali.ac.in', true),
('Indian Institute of Science Education and Research Bhopal', 'iiserb.ac.in', true),
('Indian Institute of Science Education and Research Thiruvananthapuram', 'iisertvm.ac.in', true),
('Indian Institute of Science Education and Research Berhampur', 'iiserberhampur.ac.in', true),
('Indian Institute of Science Education and Research Tirupati', 'iisertirupati.ac.in', true),

-- Central Universities
('Jawaharlal Nehru University', 'jnu.ac.in', true),
('University of Delhi', 'du.ac.in', true),
('Banaras Hindu University', 'bhu.ac.in', true),
('Aligarh Muslim University', 'amu.ac.in', true),
('Jamia Millia Islamia', 'jmi.ac.in', true),
('University of Hyderabad', 'uohyd.ac.in', true),
('Pondicherry University', 'pondiuni.edu.in', true),
('Tezpur University', 'tezu.ernet.in', true),
('North Eastern Hill University', 'nehu.ac.in', true),
('Assam University', 'aus.ac.in', true),
('Manipur University', 'manipuruniv.ac.in', true),
('Mizoram University', 'mzu.edu.in', true),
('Nagaland University', 'nagalanduniversity.ac.in', true),
('Tripura University', 'tripurauniv.ac.in', true),
('Sikkim University', 'cus.ac.in', true),
('Rajiv Gandhi University', 'rgu.ac.in', true),
('Hemvati Nandan Bahuguna Garhwal University', 'hnbgu.ac.in', true),
('Uttarakhand Technical University', 'uktech.ac.in', true),
('Central University of Himachal Pradesh', 'cuhimachal.ac.in', true),
('Central University of Punjab', 'cup.edu.in', true),
('Central University of Haryana', 'cuh.ac.in', true),
('Central University of Rajasthan', 'curaj.ac.in', true),
('Central University of Gujarat', 'cug.ac.in', true),
('Central University of Kashmir', 'cukashmir.ac.in', true),
('Central University of Jammu', 'cujammu.ac.in', true),
('Central University of Jharkhand', 'cuj.ac.in', true),
('Central University of Bihar', 'cub.ac.in', true),
('Central University of Odisha', 'cuo.ac.in', true),
('Central University of Tamil Nadu', 'cutn.ac.in', true),
('Central University of Kerala', 'cukerala.ac.in', true),
('Central University of Karnataka', 'cuk.ac.in', true),
('Central University of Andhra Pradesh', 'cuap.ac.in', true),
('Central University of Telangana', 'cuth.ac.in', true),

-- State Universities - Delhi
('Delhi Technological University', 'dtu.ac.in', true),
('Netaji Subhas University of Technology', 'nsut.ac.in', true),
('Indira Gandhi Delhi Technical University for Women', 'igdtuw.ac.in', true),
('Guru Gobind Singh Indraprastha University', 'ipu.ac.in', true),
('Ambedkar University Delhi', 'aud.ac.in', true),

-- State Universities - Maharashtra
('University of Mumbai', 'mu.ac.in', true),
('University of Pune', 'unipune.ac.in', true),
('Savitribai Phule Pune University', 'unipune.ac.in', true),
('Shivaji University', 'unishivaji.ac.in', true),
('Dr. Babasaheb Ambedkar Marathwada University', 'bamu.ac.in', true),
('Nagpur University', 'nagpuruniversity.ac.in', true),
('Solapur University', 'su.ac.in', true),
('North Maharashtra University', 'nmu.ac.in', true),
('Swami Ramanand Teerth Marathwada University', 'srtmun.ac.in', true),
('Sant Gadge Baba Amravati University', 'sgbau.ac.in', true),
('Institute of Chemical Technology', 'ictmumbai.edu.in', true),
('Tata Institute of Social Sciences', 'tiss.edu', true),
('Homi Bhabha National Institute', 'hbni.ac.in', true),

-- State Universities - Karnataka
('Bangalore University', 'bangaloreuniversity.ac.in', true),
('Mysore University', 'uni-mysore.ac.in', true),
('Karnataka University', 'kud.ac.in', true),
('Gulbarga University', 'gulbargauniversity.ac.in', true),
('Mangalore University', 'mangaloreuniversity.ac.in', true),
('Kuvempu University', 'kuvempu.ac.in', true),
('Tumkur University', 'tumkuruniversity.ac.in', true),
('Davangere University', 'davangereuniversity.ac.in', true),
('Visvesvaraya Technological University', 'vtu.ac.in', true),
('Karnataka State Open University', 'ksou.ac.in', true),

-- State Universities - Tamil Nadu
('University of Madras', 'unom.ac.in', true),
('Anna University', 'annauniv.edu', true),
('Bharathiar University', 'b-u.ac.in', true),
('Madurai Kamaraj University', 'mkuniversity.ac.in', true),
('Bharathidasan University', 'bdu.ac.in', true),
('Manonmaniam Sundaranar University', 'msuniv.ac.in', true),
('Periyar University', 'periyaruniversity.ac.in', true),
('Thiruvalluvar University', 'tvu.edu.in', true),
('Tamil University', 'tamiluniversity.ac.in', true),
('Mother Teresa Women\'s University', 'motherteresawomenuniv.ac.in', true),

-- State Universities - West Bengal
('University of Calcutta', 'caluniv.ac.in', true),
('Jadavpur University', 'jaduniv.edu.in', true),
('West Bengal University of Technology', 'wbut.ac.in', true),
('Rabindra Bharati University', 'rbu.ac.in', true),
('Visva-Bharati University', 'visva-bharati.ac.in', true),
('Kalyani University', 'klyuniv.ac.in', true),
('North Bengal University', 'nbu.ac.in', true),
('Burdwan University', 'buruniv.ac.in', true),
('Vidyasagar University', 'vidyasagar.ac.in', true),

-- State Universities - Uttar Pradesh
('Lucknow University', 'lkouniv.ac.in', true),
('Allahabad University', 'allduniv.ac.in', true),
('Kanpur University', 'kanpuruniversity.org', true),
('Agra University', 'dbrau.org.in', true),
('Gorakhpur University', 'ddu.ac.in', true),
('Meerut University', 'ccsu.ac.in', true),
('Rohilkhand University', 'mjpru.ac.in', true),
('Bundelkhand University', 'bujhansi.ac.in', true),
('Kumaun University', 'kunainital.ac.in', true),
('Uttar Pradesh Technical University', 'aktu.ac.in', true),

-- State Universities - Rajasthan
('University of Rajasthan', 'uniraj.ac.in', true),
('Rajasthan University', 'uniraj.ac.in', true),
('Jodhpur University', 'jnvu.co.in', true),
('Kota University', 'uok.ac.in', true),
('Udaipur University', 'mlsu.ac.in', true),
('Bikaner University', 'rtu.ac.in', true),
('Rajasthan Technical University', 'rtu.ac.in', true),

-- State Universities - Gujarat
('Gujarat University', 'gujaratuniversity.ac.in', true),
('Maharaja Sayajirao University of Baroda', 'msubaroda.ac.in', true),
('Saurashtra University', 'saurashtrauniversity.edu', true),
('South Gujarat University', 'vnsgu.ac.in', true),
('North Gujarat University', 'ngu.ac.in', true),
('Sardar Patel University', 'spuvvn.edu', true),
('Gujarat Technological University', 'gtu.ac.in', true),

-- State Universities - Punjab
('Panjab University', 'puchd.ac.in', true),
('Punjabi University', 'punjabiuniversity.ac.in', true),
('Guru Nanak Dev University', 'gndu.ac.in', true),
('Thapar Institute of Engineering and Technology', 'thapar.edu', true),

-- State Universities - Haryana
('Kurukshetra University', 'kuk.ac.in', true),
('Maharshi Dayanand University', 'mdu.ac.in', true),
('Chaudhary Charan Singh Haryana Agricultural University', 'hau.ac.in', true),

-- State Universities - Himachal Pradesh
('Himachal Pradesh University', 'hpuniv.ac.in', true),
('Dr. Y.S. Parmar University of Horticulture and Forestry', 'yspuniversity.ac.in', true),

-- State Universities - Jammu & Kashmir
('University of Kashmir', 'kashmiruniversity.ac.in', true),
('University of Jammu', 'jammuuniversity.ac.in', true),
('Sher-e-Kashmir University of Agricultural Sciences and Technology', 'skuastkashmir.ac.in', true),

-- State Universities - Andhra Pradesh & Telangana
('Osmania University', 'osmania.ac.in', true),
('Andhra University', 'andhrauniversity.edu.in', true),
('Kakatiya University', 'kakatiya.ac.in', true),
('Sri Venkateswara University', 'svuniversity.edu.in', true),
('Nagarjuna University', 'nagarjunauniversity.ac.in', true),
('Krishna University', 'krishnauniversity.ac.in', true),
('Jawaharlal Nehru Technological University Hyderabad', 'jntuh.ac.in', true),
('Jawaharlal Nehru Technological University Kakinada', 'jntuk.edu.in', true),
('Jawaharlal Nehru Technological University Anantapur', 'jntua.ac.in', true),

-- State Universities - Kerala
('University of Kerala', 'keralauniversity.ac.in', true),
('Cochin University of Science and Technology', 'cusat.ac.in', true),
('Calicut University', 'uoc.ac.in', true),
('Mahatma Gandhi University', 'mgu.ac.in', true),
('Kannur University', 'kannuruniv.ac.in', true),
('Kerala Agricultural University', 'kau.in', true),

-- State Universities - Odisha
('Utkal University', 'utkaluniversity.ac.in', true),
('Sambalpur University', 'suniv.ac.in', true),
('Berhampur University', 'bamu.nic.in', true),
('North Orissa University', 'nou.nic.in', true),
('Fakir Mohan University', 'fmuniversity.ac.in', true),

-- State Universities - Bihar & Jharkhand
('Patna University', 'patnauniversity.ac.in', true),
('Magadh University', 'magadhuniversity.ac.in', true),
('Bihar University', 'biharuniversity.ac.in', true),
('Ranchi University', 'ranchiuniversity.ac.in', true),
('Birsa Agricultural University', 'bauranchi.org', true),

-- State Universities - Assam & Northeast
('Gauhati University', 'gauhati.ac.in', true),
('Dibrugarh University', 'dibru.ac.in', true),
('Cotton University', 'cottonuniversity.ac.in', true),

-- State Universities - Madhya Pradesh & Chhattisgarh
('Devi Ahilya Vishwavidyalaya', 'dauniv.ac.in', true),
('Jiwaji University', 'jiwaji.edu', true),
('Rani Durgavati University', 'rdunijbpin.org', true),
('Vikram University', 'vikramuniv.ac.in', true),
('Barkatullah University', 'bubhopal.ac.in', true),
('Pt. Ravishankar Shukla University', 'prsu.ac.in', true),

-- Deemed Universities
('Birla Institute of Technology and Science', 'bits-pilani.ac.in', true),
('Manipal Academy of Higher Education', 'manipal.edu', true),
('VIT University', 'vit.ac.in', true),
('SRM Institute of Science and Technology', 'srmist.edu.in', true),
('Amrita Vishwa Vidyapeetham', 'amrita.edu', true),
('Kalinga Institute of Industrial Technology', 'kiit.ac.in', true),
('Lovely Professional University', 'lpu.in', true),
('Shoolini University', 'shooliniuniversity.com', true),
('Chitkara University', 'chitkara.edu.in', true),
('Bennett University', 'bennett.edu.in', true),
('Ashoka University', 'ashoka.edu.in', true),
('O.P. Jindal Global University', 'jgu.edu.in', true),
('Flame University', 'flame.edu.in', true),
('Symbiosis International University', 'siu.edu.in', true),
('Christ University', 'christuniversity.in', true),
('Jain University', 'jainuniversity.ac.in', true),
('PES University', 'pes.edu', true),
('Dayananda Sagar University', 'dsu.edu.in', true),
('REVA University', 'reva.edu.in', true),
('Alliance University', 'alliance.edu.in', true),
('Azim Premji University', 'azimpremjiuniversity.edu.in', true),
('JSS Academy of Higher Education and Research', 'jssuni.edu.in', true),
('Nitte University', 'nitte.edu.in', true),
('Karunya Institute of Technology and Sciences', 'karunya.edu', true),
('Kalasalingam Academy of Research and Education', 'klu.ac.in', true),
('Hindustan Institute of Technology and Science', 'hindustanuniv.ac.in', true),
('Sathyabama Institute of Science and Technology', 'sathyabama.ac.in', true),
('Vel Tech Rangarajan Dr. Sagunthala R&D Institute', 'veltech.edu.in', true),

-- Medical Colleges
('All India Institute of Medical Sciences Delhi', 'aiims.ac.in', true),
('All India Institute of Medical Sciences Bhopal', 'aiimsbhopal.edu.in', true),
('All India Institute of Medical Sciences Bhubaneswar', 'aiimsbhubaneswar.edu.in', true),
('All India Institute of Medical Sciences Jodhpur', 'aiimsjodhpur.edu.in', true),
('All India Institute of Medical Sciences Patna', 'aiimspatna.org', true),
('All India Institute of Medical Sciences Raipur', 'aiimsraipur.edu.in', true),
('All India Institute of Medical Sciences Rishikesh', 'aiimsrishikesh.edu.in', true),
('Christian Medical College Vellore', 'cmcvellore.ac.in', true),
('Armed Forces Medical College', 'afmc.nic.in', true),
('King George\'s Medical University', 'kgmcindia.edu', true),
('Postgraduate Institute of Medical Education and Research', 'pgimer.edu.in', true),
('Sanjay Gandhi Postgraduate Institute of Medical Sciences', 'sgpgi.ac.in', true),
('National Institute of Mental Health and Neurosciences', 'nimhans.ac.in', true),

-- Law Universities
('National Law School of India University', 'nls.ac.in', true),
('National Academy of Legal Studies and Research', 'nalsar.ac.in', true),
('The West Bengal National University of Juridical Sciences', 'nujs.edu', true),
('Rajiv Gandhi School of Intellectual Property Law', 'rgnul.ac.in', true),
('Gujarat National Law University', 'gnlu.ac.in', true),
('Hidayatullah National Law University', 'hnlu.ac.in', true),
('Jamia Millia Islamia Faculty of Law', 'jmi.ac.in', true),

-- Agricultural Universities
('Indian Agricultural Research Institute', 'iari.res.in', true),
('Punjab Agricultural University', 'pau.edu', true),
('Tamil Nadu Agricultural University', 'tnau.ac.in', true),
('University of Agricultural Sciences Bangalore', 'uasbangalore.edu.in', true),
('Acharya N.G. Ranga Agricultural University', 'angrau.ac.in', true),
('Orissa University of Agriculture and Technology', 'ouat.ac.in', true),

-- Fashion and Design Institutes
('National Institute of Design', 'nid.edu', true),
('National Institute of Fashion Technology Delhi', 'nift.ac.in', true),
('Pearl Academy', 'pearlacademy.com', true),

-- Management and Business Schools
('Indian School of Business', 'isb.edu', true),
('Xavier Labour Relations Institute', 'xlri.ac.in', true),
('S.P. Jain Institute of Management and Research', 'spjimr.org', true),
('Management Development Institute', 'mdi.ac.in', true),
('Faculty of Management Studies Delhi', 'fms.edu', true),
('Indian Institute of Foreign Trade', 'iift.edu', true),

-- Specialized Institutes
('Indian Statistical Institute', 'isical.ac.in', true),
('Indian Institute of Space Science and Technology', 'iist.ac.in', true),
('Defence Institute of Advanced Technology', 'diat.ac.in', true),
('Indian Maritime University', 'imu.ac.in', true),
('Rajiv Gandhi Institute of Petroleum Technology', 'rgipt.ac.in', true),
('Indian Institute of Petroleum and Energy', 'iipe.ac.in', true),
('National Institute of Technology and Management', 'nitm.ac.in', true);
